[package]
name = "hyksa"
version = "0.1.0"
authors = ["daniel"]

[dependencies]
rustbox = "0.6.2"
rustc-serialize = "0.3"
itertools = "0.3.24"
log = "0.3"
env_logger = "0.3"
gag = "0.1"
toml = "0.1"

docopt = "0.6"
