[package]
name = "rex"
version = "0.1.0"
authors = ["dbrodie@gmail.com"]
description = "A lean hex editor"
keywords = ["hex", "editor"]
repository = "https://github.com/dbrodie/rex"
license = "MIT"
readme = "README.md"

[dependencies]
rustc-serialize = "0.3"
itertools = "0.4"
log = "0.3"
env_logger = "0.3"
gag = "0.1"
toml = "0.1"
docopt = "0.6"

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox.git"
rev = "1fa89a5a6c8109e15bbafb897f3956081943c838"

[dependencies.rex_utils]
path = "rex_utils"
